<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\VGS.RetailOS.Shared\VGS.RetailOS.Shared.csproj" />
    <ProjectReference Include="..\..\Contracts\VGS.RetailOS.Contracts\VGS.RetailOS.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
